### ISSUE TITLE
HolderCreator 数据类型，为什么不使用泛型呢?

### ISSUE THREAD

**Issue by zxqSmile** [zguop/banner#1]
![image](https://user-images.githubusercontent.com/16300382/71944282-48241580-31fe-11ea-8505-469a27b9b124.png)
Object o，这个数据为什么不使用泛型呢，是有别的考虑吗?

**Comment by zguop** [comment]
@zxqSmile 这个有在考虑要不要加一下呢，由于Banner上没有声明泛型，setHolderCreator，setPages又是分开两个方法调用的，如果接口上声明的实际类型和传递的数据不一致，就会报错，想法是使用者自己强转一下
