### ISSUE TITLE
请问想要实现展示完整的第一个,和只有一半的第二个该怎么做呢?我看这个库好像没有这样的效果

### ISSUE THREAD

**Issue by roybill** [zguop/banner#12]
如果没有的话,作者可否加上这个功能呢?谢谢

**Comment by zguop** [comment]
@roybill 你有实际效果贴一下么

**Comment by roybill** [comment]
这里回复要添加网络图片,发不了呀,可否留个邮箱呢?我看了一下你这边的说明,我试试左边露出来的值改为0不知道行不行,你的说明是这样的:
//设置左右页面露出来的宽度及item与item之间的宽度
.setPageMargin(UIUtil.dip2px(this, 20), UIUtil.dip2px(this, 10))
//内置ScaleInTransformer，设置切换缩放动画
.setPageTransformer(true, new ScaleInTransformer())

**Comment by zguop** [comment]
374735994@qq.com

**Comment by roybill** [comment]
还有这边源码里面没有找到UIUtil这个类哦,希望能够加上去,谢谢

**Comment by zguop** [comment]
这个dp转换 都在别的库里直接拿来用了。 也可以用SizeUtils

**Comment by roybill** [comment]
想要实现的效果图已经发送到你的邮箱了,请查收一下

**Comment by roybill** [comment]
用上了第三个参数就可以了,非常感谢,我再优化一下.我这样设置的:
        IndicatorView qyIndicator = new IndicatorView(this)
                .setIndicatorColor(Color.DKGRAY)
                .setIndicatorSelectorColor(Color.WHITE);
        banner.setIndicator(qyIndicator)
                .setPageMargin(0, 100,10)
                .setPageTransformer(true, new ScaleInTransformer())
                .setHolderCreator(new ImageHolderCreator())
                .setPages(list);

**Comment by zguop** [comment]
@roybill  没有缩放效果 .setPageTransformer(true, new ScaleInTransformer()) 这个就不需要设置

**Comment by roybill** [comment]
谢谢

**Comment by roybill** [comment]
还有一个疑问,想要关闭无限轮播怎么设置呢?就是当我在第一页的时候,往左滑动是想要没有任何操作的,我看到这个setAutoPlay(boolean false)只是设置是否自动轮播的功能.

**Comment by zguop** [comment]
@roybill 这个是无限轮播的控件，如果你的需求是 不需要无限轮播的话 直接用viewpager就可以了 对viewpager设置下面属性

**Comment by zguop** [comment]
目前还没有考虑到关闭无限轮播呢，因为不使用无限轮播的功能，就可以直接使用ViewPager。我是这样想的

**Comment by roybill** [comment]
好的,谢谢
