### ISSUE TITLE
banner點擊兩側 position錯誤

### ISSUE THREAD

**Issue by PascalTang** [zguop/banner#13]
val adapter = OriginVideoAdapter(R.layout.item_origin_banner, arrayListOf())

        adapter.setOnItemClickListener { holder, view, position ->
            Timber.tag("ddd").i("click $position")
            Timber.tag("ddd").i("click2 "+mBanner?.currentPager)
        }

你好 我是用viewpager2版本
我的banner有留左右的影片 也就是一頁三式
但當我點擊非中間的影片時
get的current position仍是中間的
但setOnItemClickListener的position位置會是正確的（可是他不是data實際的position）
請問我想要監聽是否點擊 兩側的影片
要如何取到他的值？

**Comment by zguop** [comment]
轮播是实际的item + 2的情况，然后 BaseQuickAdapter  if (getOnItemClickListener() != null) {
            view.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    int position = baseViewHolder.getAdapterPosition();
                    if (position == RecyclerView.NO_POSITION) {
                        return;
                    }
                    position -= getHeaderLayoutCount();
                    setOnItemClick(v, position);
                }
            });
        }

**Comment by PascalTang** [comment]
非常感謝
