### ISSUE TITLE
請問是否支持禁止無限循環設定

### ISSUE THREAD

**Issue by money150604** [zguop/banner#14]
請問是否支持禁止無限循環設定

**Comment by zguop** [comment]
@money150604 目前是不支持的。

**Comment by wojiaojay123** [comment]
> @money150604 目前是不支持的。 请问什么场景中禁止循环？

不同的产品会有不同的需求，我们也是不需要无限循环，希望加一个字段控制，谢谢

**Comment by zguop** [comment]
@wojiaojay123 如果不需要无限循环 ，用原生的不就好了吗？？？

**Comment by wojiaojay123** [comment]
> @wojiaojay123 如果不需要无限循环 ，用原生的不就好了吗？？？

我们的需求是没有无限滑动，但是有一页显示3张图的需求，所以用了您写的这个库，我个人感觉您可以支持一下
