### ISSUE TITLE
使用FragmentStateAdapter 会看不到内容

### ISSUE THREAD

**Issue by heimaxiaobo** [zguop/banner#17]
使用FragmentStateAdapter 会看不到内容
androidx.viewpager2.adapter.FragmentStateAdapter

**Comment by zguop** [comment]
@heimaxiaobo 我在demo试试看

**Comment by heimaxiaobo** [comment]
@zguop 应该很好复现的

**Comment by heimaxiaobo** [comment]
我现在如果直接实现Adapter是能用的，但是有个问题，我实现无限轮播的同时也在刷新数据，但是会出现滑动卡顿的现象

**Comment by heimaxiaobo** [comment]
请问有解决的办法吗，有的话我就不需要FragmentStateAdapter，来另找途径了

**Comment by zguop** [comment]
@heimaxiaobo 每次滑动切换都会刷数据吗

**Comment by heimaxiaobo** [comment]
我这边需求是要滑出新的数据来

**Comment by zguop** [comment]
滑动尾部加载新数据？ 我现在还不确定适不适合你这样的场景

**Comment by heimaxiaobo** [comment]
就是不确定,我才想试试FragmentStateAdapter,通过Fragment来处理数据，看看能解决卡顿问题不

**Comment by zguop** [comment]
可以录的gif发我邮箱 374735994@qq.com

**Comment by o0o0oo00** [comment]
我也发现确实有这个问题，很诡异，就不用FragmentStateAdapter了，直接写Recyclerview.adapter了
