### ISSUE TITLE
嵌套ViewPager2的一个小问题

### ISSUE THREAD

**Issue by Coyamo** [zguop/banner#19]
把Banner嵌套在ViewPager里面，现在是Banner滑动完毕会触发外面嵌套的ViewPager的滑动。
如果可以，希望增加一个完全拦截滑动的设置，就是Banner滑动到最后一个再滑动，不会滑动外面的pager，而是把banner滑动到第一个。

**Comment by Coyamo** [comment]
上面没说清楚，主要是滑动嵌套的banner很容易触发外面的pager，仔细滑动banner还是可以循环滑动的。希望把触发滑动的范围搞大一点

**Comment by zguop** [comment]
、是不是跟#15一个问题

**Comment by Coyamo** [comment]
> @Coyamo 你用在用的哪个版本？ 、是不是跟#15一个问题

viewpager2版本的最新依赖

是一样的。不好意思没注意到已经有人提了

**Comment by zguop** [comment]
@Coyamo 恩 我会再修改修改那个事件触发的值
