### ISSUE TITLE
appbarlayout nestedscrollview 滑动联动问题

### ISSUE THREAD

**Issue by wwy863399246** [zguop/banner#20]
nestedscrollview 顶部用该banner 按住banner上滑 滑动联动会失效

**Comment by zguop** [comment]
nestedscrollview .setNestedScrollingEnabled(false);  试试

**Comment by wwy863399246** [comment]
不行的 不过把banner里面的viewpage2的滑动禁止掉就可以按住banner滑动 并且联动了

**Comment by wwy863399246** [comment]
应该是事件冲突的问题 我外部拦截过 划一下可以 但是按住banner就不行了

**Comment by zguop** [comment]
RecyclerView recyclerView = (RecyclerView) banner.getViewPager2().getChildAt(0);
recyclerView.setNestedScrollingEnabled(false); 应该是这样 我记得之前有人提过这样的问题

**Comment by wwy863399246** [comment]
可以了，三扣
