### ISSUE TITLE
recyclerView的demo，用addHeader添加的banner，快速滑到下面再划回来，banner有时候会卡在两张图片中间

### ISSUE THREAD

**Issue by DevYJQ** [zguop/banner#21]
RT
![image](https://user-images.githubusercontent.com/38904992/84729992-9ae0d500-afc7-11ea-9d22-c9a929feebf5.png)

**Comment by zguop** [comment]
ViewPager2吗

**Comment by DevYJQ** [comment]
是viewpager的

**Comment by lhf686868** [comment]
我是viewPager2首次加载轮播图的时候会出现图片卡一半

**Comment by zguop** [comment]
@lhf686868  demo中的场景看看  满足你不
