### ISSUE TITLE
循环拖动

### ISSUE THREAD

**Issue by xiangxm** [zguop/banner#23]
请问博主，viewPager2 可以循环拖动，这个主要的控制代码是哪些？  想借鉴一下如何实现的，但是看了代码没有找到这部分

**Comment by zguop** [comment]
onPageScrollStateChanged 和 task 里的run方法 你看看吧

**Comment by xiangxm** [comment]
> onPageScrollStateChanged 和 task 里的run方法 你看看吧

谢谢，当viewpager2 滑到最后一张的时候还可以继续滑这个处理是在哪里？ 我本地的滑到最后就划不动了

**Comment by zguop** [comment]
onPageScrollStateChanged 这方法处理的 手动滑
