### ISSUE TITLE
混淆后出问题

### ISSUE THREAD

**Issue by wangchengmeng** [zguop/banner#24]
混淆后就出问题了，有没有人贴出混淆代码呢

**Comment by zguop** [comment]
-keep 掉呗

**Comment by zguop** [comment]
-keep class com.to.aboomy.banner.**{*;} 你试试 

不过我自己项目用这个没有配混淆的

**Comment by wangchengmeng** [comment]
-keep class com.to.aboomy.pager2banner.** {*;}
-keep class androidx.viewpager2.widget.**{*;}

添加上这个混淆代码 就没问题了，
