### ISSUE TITLE
设置指示器的圆点距离底部的距离问题；

### ISSUE THREAD

**Issue by jeffreyxuworld** [zguop/banner#25]
RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        params.addRule(RelativeLayout.ALIGN_PARENT_BOTTOM);
        params.addRule(RelativeLayout.CENTER_HORIZONTAL);
        params.bottomMargin = CommonUtil.dip2px(12);
--------------------------
        IndicatorView indicatorView = new IndicatorView(getActivity())
                .setIndicatorRatio(1f) //ratio，默认值是1 ，也就是说默认是圆点，根据这个值，值越大，拉伸越长，就成了矩形，小于1，就变扁了
                .setIndicatorRadius(4f) //radius 点的大小
                .setIndicatorSelectedRatio(1f)
                .setIndicatorSelectedRadius(4f)
                .setIndicatorSpacing(6f)
                .setIndicatorStyle(IndicatorView.IndicatorStyle.INDICATOR_CIRCLE)
                .setIndicatorColor(getResources().getColor(R.color.color_4b525f))
                .setParams(params)
                .setIndicatorSelectorColor(getResources().getColor(R.color.color_FFE7B6));
-----------------------

params.bottomMargin = CommonUtil.dip2px(12); 设置指示器的圆点距离底部的距离，.setParams(params)在一些布局场景，会无效。距离底部距离为0

**Comment by jeffreyxuworld** [comment]
如果通过xml布局的方式添加IndicatorView，也会报这个错：
The specified child already has a parent. You must call removeView() on the child's parent first 
可以把这个代码改为：
    /**
     * 设置indicator，支持在xml中创建
     *
     * @param attachToRoot true 添加到banner布局中
     */
    public Banner setIndicator(Indicator indicator, boolean attachToRoot) {
        if (this.indicator != null) {
            removeView(this.indicator.getView());
        }
        if (indicator != null) {
            this.indicator = indicator;
            if (attachToRoot) {
                **if(this.indicator.getView().getParent() != null) {
                    ((ViewGroup)this.indicator.getView().getParent()).removeView(this.indicator.getView()); // <- fix
                }**
                addView(this.indicator.getView(), this.indicator.getParams());
            }
        }
        return this;
    }

**Comment by zguop** [comment]
你写在xml中的话 public Banner setIndicator(Indicator indicator, boolean attachToRoot)  attachToRoot写 false吧 ？

**Comment by jeffreyxuworld** [comment]
> 你写在xml中的话 public Banner setIndicator(Indicator indicator, boolean attachToRoot) attachToRoot写 false吧 ？
> 你在xml中调整好位置就好了
attachToRoot用的true,改成false确实好了。
谢谢。
