### ISSUE TITLE
banner 上有视频播放器 会冲突的问题

### ISSUE THREAD

**Issue by xyggs** [zguop/banner#28]
作者好 ，  我在首页banner 上面放着有  视频播放器，  那个banner库 重写了dispatchTouchEvent， 执行按下 暂停轮播，松开继续轮播的效果。。。和视频播放起冲突起来了，，，   点击视频播放器， 会浮现各个功能按钮出来嘛，， 现在 点下视频播放器，2S后  就自个儿轮播了。。。这个有什么好的解决办法没呀

**Comment by zguop** [comment]
你想点下播放器 停止轮播 ？ 还是你想要什么效果呢

**Comment by xyggs** [comment]
就是 停止轮播。我现在是把源码复制了改的。。通过参数控制是否执行 banner 里 dispatchTouchEvent 内的方法

**Comment by zguop** [comment]
setAutoPlay(boolean autoPlay) 有这个方法提供 
当然直接用源码你看着修改修改也是可以的哈
