### ISSUE TITLE
点击banner滑动，无法与appbar_scrolling_view_behavior联动

### ISSUE THREAD

**Issue by mapsh** [zguop/banner#3]
如题
banner 设置水平滚动，外层NestedScrollView垂直滚动

**Comment by zguop** [comment]
@mapsh 有具体代码片段么，怎么个联动？可以私发374735994@qq.com

**Comment by zguop** [comment]
@mapsh   banner.getViewPager2().getChildAt(0).setNestedScrollingEnabled(false); 貌似就解决了这个问题，你可以试一下
