### ISSUE TITLE
bug：自动播放时一次跳两页

### ISSUE THREAD

**Issue by tao-glow** [zguop/banner#31]
startTurning 连续调用会导致 task 被重复执行，我这里表现的bug就是一次跳两页

解决办法：
```
public void stopTurning() {
        removeCallbacks(task);
}
```
改成：
```
private final Handler handler = new Handler(Looper.getMainLooper());
public synchronized void stopTurning() {
        handler.removeCallbacksAndMessages(null);
    }
```

**Comment by zguop** [comment]
![image](https://user-images.githubusercontent.com/16206793/103400584-9e613580-4b80-11eb-9089-ab14555b971e.png)

   public void startTurning() {
        stopTurning();
        postDelayed(task, autoTurningTime);
    }

内部方法是会先停止再调用的，你是怎么操作的

**Comment by tao-glow** [comment]
```
indicator
        .setIndicatorColor(resources.getColor(R.color.green_apple_light))
        .setIndicatorSelectorColor(resources.getColor(R.color.green_apple))
    banner.setIndicator(indicator, false)
    banner.adapter = BannerAdapter()
```
我这样使用就会重现，我跑了了你的demo确实没问题，看代码是 attachWindow和setAdapter 的时候都调用了startTurning, 其实 attachWindow里的 startTurning 可以注释掉，但是这样没解决根本问题，后来查了一下是 removeCallbacks 的问题

https://stackoverflow.com/questions/26546043/android-handler-removecallbacks-not-working

**Comment by zguop** [comment]
测试出来了 不能多次调用stopTurning   我加个标记解决一下
