### ISSUE TITLE
CoordinatorLayout+AppbarLayout+NestedScrollView滑动冲突 只会滑动下面的布局 appbarLayout不会跟着滑动

### ISSUE THREAD

**Issue by ts-xiaoa-521** [zguop/banner#34]
CoordinatorLayout+AppbarLayout+NestedScrollView滑动冲突 只会滑动下面的布局 appbarLayout不会跟着滑动  banner放在NestedScrollView布局中，NestedScrollView嵌套RecycleView设置android:nestedScrollingEnabled="false"就行了，但是这个不行。给ViewPager2设置也不行

**Comment by zguop** [comment]
看 #20
