### ISSUE TITLE
一屏三个半，然后滑动，将出现空白

### ISSUE THREAD

**Issue by zhangyin2019** [zguop/banner#37]
一屏三个半，然后滑动，将出现空白

**Comment by zguop** [comment]
细节呢 怎么出现

**Comment by zhangyin2019** [comment]
![image](https://user-images.githubusercontent.com/49790909/111977733-0b5fe800-8b3e-11eb-9f92-9d8eb0d796ce.png)
就是这种滑动几次以后就出现空白，就是后面没有连续了

**Comment by zhangyin2019** [comment]
一屏1、2个没问题，只有三个及以上的时候

**Comment by zguop** [comment]
你看下运行下demo 看看 =
实际效果图没有吗

**Comment by zhangyin2019** [comment]
![image](https://user-images.githubusercontent.com/49790909/111979835-81fde500-8b40-11eb-9faf-81959d8c44dc.png)

**Comment by zguop** [comment]
可以实现这种效果么。= =  用了Transformer？
