### ISSUE TITLE
如何设置当前页的效果

### ISSUE THREAD

**Issue by MonkeyEatBanana** [zguop/banner#43]
比如当前选中页的字体颜色变换

**Comment by zguop** [comment]
setOuterPageChangeListener 不是可以监听么

**Comment by MonkeyEatBanana** [comment]
对，我也是这么做的，可是通过数据做处理后，刷新，过渡的动画就没有了

**Comment by MonkeyEatBanana** [comment]
![image](https://user-images.githubusercontent.com/16996824/136637832-444a869d-df78-4dc2-96ba-89be0f2b7be7.png)

**Comment by MonkeyEatBanana** [comment]
@zguop

**Comment by zguop** [comment]
374735994 沟通下吧 没懂唉
