### ISSUE TITLE
indicator 要設置在veiwpager之外 有辦法解決嗎？

### ISSUE THREAD

**Issue by nikeru8** [zguop/banner#44]
如題
indicator 要設置在veiwpager之外 有辦法解決嗎？
有辦法設置嗎？

**Comment by zguop** [comment]
demo里有姿势  ，第二个false

setIndicator(Indicator indicator, boolean attachToRoot)



<br class="Apple-interchange-newline">

**Comment by nikeru8** [comment]
剛看了demo 全域搜尋裡面沒有 setIndicator(Indicator indicator, FALSE)的範例

**Comment by zguop** [comment]
你使用这个方法就可以了，可以将 Indicator 写到任意地方（xml也可以）。 传入 false表示不添加到banner布局中，但是你自己要管理好 Indicator 摆放的位置

**Comment by zguop** [comment]
MultPager2BannerActivity 这个里面有
