### ISSUE TITLE
滑動到最後一頁後，右滑不要回到第一頁 有停止方法嗎？

### ISSUE THREAD

**Issue by nikeru8** [zguop/banner#45]
如題

**Comment by zguop** [comment]
不轮播 直接用viewpager2 就好

**Comment by nikeru8** [comment]
我想要你的indicator效果

**Comment by zguop** [comment]
viewpager2 设置监听 调用 indicator 的每个方法就行了 试试

**Comment by zguop** [comment]
调用 indicator 的 onPageScrolled 这个

**Comment by nikeru8** [comment]
範例內有嗎？
我去找來看看

**Comment by zguop** [comment]
![image](https://user-images.githubusercontent.com/16206793/138089280-16aca462-2092-4fbc-9949-7efe41f0ce82.png)
