### ISSUE TITLE
我的banner无法一直无限滑动

### ISSUE THREAD

**Issue by FightingForDevelop** [zguop/banner#46]
我写了Demo是没有问题的,可以一直划,但是加到项目中就不能无限滑动,使用的是com.to.aboomy.pager2banner.Banner,自己实现了recyclerviewadapter 轮播不同样式的布局.
比如我有3条数据,实际banner在左右各新增了一条,也就是这个库的实现原理,但是划到头的时候并没有切到最后一个,求解答

**Comment by zguop** [comment]
使用姿势不对？

**Comment by FightingForDevelop** [comment]
> 

不清楚,设置自动混播,倒是可以播,不过可以看出来往回走了,感觉设置的viewPager2.setCurrentItem(sidePage, false);没有生效.如果是手动一直往一个方向滑动,就会出现滑不动的现象

**Comment by FightingForDevelop** [comment]
我断点看了,自动轮播切换的position没有问题,但是动画效果不是静默切换的,受什么影响呢,我没有自定义transform动画

**Comment by zguop** [comment]
374735994帮助你看看

**Comment by AriesHaw** [comment]
我也遇到同样的问题 看起来是设置的viewPager2.setCurrentItem(sidePage, false) 没有生效 滑到两端的时候无法继续滑动了
