### ISSUE TITLE
Proguard後Banner無法無限滑動, Indicator也不會動

### ISSUE THREAD

**Issue by martinboy1020** [zguop/banner#47]
我測試沒有Proguard的時候, Banner是可以正常無限滑動的, 但不知道為什麼只要有做了Proguard後,  Banner就不能無限滑動而且連Indicator都有問題

**Comment by zguop** [comment]
#40

**Comment by martinboy1020** [comment]
看起來應該是ViewPager2被混淆的問題
-keep class androidx.viewpager2.widget.**{;}
Keep ViewPager2就正常了, 感謝
