### ISSUE TITLE
ViewPager2嵌套问题

### ISSUE THREAD

**Issue by open9527** [zguop/banner#5]
请问下大佬知道ViewPager2嵌套ViewPager2 的解决方案吗?

**Comment by slantingHead** [comment]
@open9527 ViewPager2嵌套使用，我有时间去测试一下看看。你有遇到什么具体的问题，方便提供给我参考吗？

**Comment by zguop** [comment]
@open9527 ViewPager2嵌套使用，我有时间去测试一下看看。你有遇到什么具体的问题，方便提供给我参考吗？

**Comment by Dazzworld** [comment]
会无法滑动

**Comment by open9527** [comment]
@zguop 当然不是说你的控件,只是咨询下能解决ViewPager2嵌套ViewPager2 滑动问题么?会冲突

**Comment by zguop** [comment]
@open9527 @Dazzworld com.to.aboomy:pager2banner:0.0.3 抽空修复了，感谢支持哈。具体实现可以到源码中查看~
