### ISSUE TITLE
问一问能不能在fragment上用

### ISSUE THREAD

**Issue by 8056** [zguop/banner#7]
在fragment上setHolderCreator报空指针怎么办

**Comment by zguop** [comment]
@8056 你是怎么使用的？

**Comment by 8056** [comment]
![)7ZFP4W6$~HDAAYTLZMGRB2](https://user-images.githubusercontent.com/60913449/77272753-e77c8300-6cec-11ea-8cfa-0113ebccbe2b.png)
![}YQSEDBYV2$KB(4PCS{7Y8B](https://user-images.githubusercontent.com/60913449/77272755-e8151980-6cec-11ea-9ca9-82c7b9e8100f.png)
![UUXSKJCDHN4C47RK~IY{(4V](https://user-images.githubusercontent.com/60913449/77272776-f3684500-6cec-11ea-85d4-e1599a06bbb1.png)

**Comment by 8056** [comment]
大佬好，我是在Fragment的onActivityCreated方法中初始化banner的，但是setHolderCreator后面的参数不知道该怎么填

**Comment by zguop** [comment]
@8056  这么写，你这个空指针 和 setHolderCreator 没关系吧  你是banner为空么？

**Comment by 8056** [comment]
报错信息在这里
![S%RJE(@28D(7MSC_Z8(A64G](https://user-images.githubusercontent.com/60913449/77284233-27e9fa00-6d09-11ea-8fbd-82bb808829d0.png)


> @8056 这么写，你这个空指针 和 setHolderCreator 没关系吧 你是banner为空么？

**Comment by 8056** [comment]
用getActivity也不行

**Comment by zguop** [comment]
@8056 你检查下你init方法传入的banner 为null 了

**Comment by 8056** [comment]
嗷，就是的就是的，是自己粗心了，谢谢

> @8056 你检查下你init方法传入的banner 为null 了
