### ISSUE TITLE
page 0時 ui error

### ISSUE THREAD

**Issue by PascalTang** [zguop/banner#8]
當我輪播時
到第二輪 page 0
最右邊不會出現page1的畫面
而是會透到底層的fragment
原本的banner沒這個問題
.setPageMargin(UIUtil.dip2px(this, 20), UIUtil.dip2px(this, 10))

**Comment by PascalTang** [comment]
原本的banner沒這個問題

**Comment by zguop** [comment]
@PascalTang 请问用的哪个版本的banner

**Comment by PascalTang** [comment]
最新的 banner2 viewpager2改的那個
