### ISSUE TITLE
BaseQuickAdapter get item 

### ISSUE THREAD

**Issue by PascalTang** [zguop/banner#9]
你好
再問一個問題
我的需求是
能在banner顯示時 再BaseQuickAdapter內執行ui上某件事
但我觀察convert是一次創好的
這樣我要如何才能抓到實際上position的view item?

**Comment by zguop** [comment]
@PascalTang  你要获取非实际data的position吗？
外部：banner.getViewPager2().getCurrentItem()
adapter内部： holder.getAdapterPosition()
获取真实位置：banner.getCurrentPager()
你看看是否满足你。

**Comment by PascalTang** [comment]
ok 這個可以
另外問一個
如果我想add view進去
但在觸發OnPageChangeCallback時
會比convert
導致內部的view根本還沒創建完
有什麼好解法嗎

**Comment by PascalTang** [comment]
我希望的是 有同一個view 能在viewpager2裡面 搬來搬去

**Comment by zguop** [comment]
@PascalTang @PascalTang  尴尬了 我不是很懂 具体点呗

**Comment by zguop** [comment]
HolderRestLoader 你看看这个接口

**Comment by PascalTang** [comment]
就是我有個播放器
但我希望所有的item view 共用同一個播放器的實體
我暫時用
  val recycle = banner.viewPager2.getChildAt(0) as RecyclerView
  val itemView = recycle.layoutManager?.findViewByPosition(realPosition)as ConstraintLayout?
itemView add/remove
暫時解掉了
感謝
